version: 2
jobs:
  build:
    docker:
      # Use node image
      - image: circleci/node:10

    # code folder
    working_directory: ~/repo

    steps:
      # check out code
      - checkout

      # restore cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # install and cache packages
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # audit the pacakges
      - run: npm audit
      - run: npm ls

      # security test
      - run: snyk test

      # check the package lock file
      - run: ./node_modules/.bin/check-package-lock

      # correct line endings
      - run: find ./*.js ./*.json ./*.md test/*.js | xargs lintspaces --endofline 'lf' --newline --trailingspaces --verbose
      - run: find test/ -name '*.css' | xargs lintspaces --endofline 'lf' --newline --trailingspaces --verbose

      # lint
      - run: eslint '*.js' 'test/*.js'

      # run tests
      - run: ./node_modules/.bin/nyc npm test

      # upload code coverage
      - run: ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
      - run: ./node_modules/.bin/codecov
